//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class allowance
    {
        public string EmpClassID { get; set; }
        public decimal HouseAllowance { get; set; }
        public decimal ConveyanceAllowance { get; set; }
        public decimal MedicalAllowance { get; set; }
        public decimal StatutoryBonus { get; set; }
        public decimal SupplementaryAllowance { get; set; }
    
        public virtual PayrollMain PayrollMain { get; set; }
    }
}
