//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpClass
    {
        public string EmpClassID { get; set; }
        public string EmpClass1 { get; set; }
        public decimal ClassSalary { get; set; }
    
        public virtual PayrollMain PayrollMain { get; set; }
    }
}
