//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpPayroll
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpPayroll()
        {
            this.PayrollMains = new HashSet<PayrollMain>();
        }
    
        public string EmpID { get; set; }
        public string Name { get; set; }
        public string Father_Name { get; set; }
        public string Mother_Name { get; set; }
        public System.DateTime DOB { get; set; }
        public string Gender { get; set; }
        public string Nationality { get; set; }
        public string Maritual_Status { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string Present_Address { get; set; }
        public string Permanent_Address { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Gross_Salary { get; set; }
        public string Attendence_Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PayrollMain> PayrollMains { get; set; }
    }
}
