//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollDLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class payrollEntities : DbContext
    {
        public payrollEntities()
            : base("name=payrollEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmpPayroll> EmpPayrolls { get; set; }
        public virtual DbSet<PayrollMain> PayrollMains { get; set; }
        public virtual DbSet<allowance> allowances { get; set; }
        public virtual DbSet<Deduction> Deductions { get; set; }
        public virtual DbSet<EmpClass> EmpClasses { get; set; }
    }
}
