//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayrollDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayrollMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PayrollMain()
        {
            this.allowances = new HashSet<allowance>();
            this.Deductions = new HashSet<Deduction>();
            this.EmpClasses = new HashSet<EmpClass>();
        }
    
        public string EmpID { get; set; }
        public string EmpClassID { get; set; }
        public string EmpClass { get; set; }
        public string Designation { get; set; }
        public string Password { get; set; }
    
        public virtual EmpPayroll EmpPayroll { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<allowance> allowances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Deduction> Deductions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmpClass> EmpClasses { get; set; }
    }
}
